services:
  - type: web
    name: django-quote-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.wsgi
    envVars:
      - key: SECRET_KEY
        fromDatabase: true
      - key: ALLOWED_HOSTS
        fromDatabase: true
