services:
  - type: web
    name: quote-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn api.wsgi:application
    envVars:
      - key: SECRET_KEY
        fromDatabase: true
      - key: ALLOWED_HOSTS
        fromDatabase: true
